### ISSUE TITLE
请问这个是不能用了吗？

### ISSUE THREAD

**Issue by shacoqian** [quant1x/gotdx#3]
调用获取线 然后这个提示 

尊敬的投资者：您当前使用的招商证券交易软件已长期停止更新维护，且后续不再提供更新维护，存在交易、理财功能缺失，存在账户安全风险隐患，可能会造成您的财产权益损失。
    现我司决定将于2023年8月31日将此客户端下线停止使用，我司已提供招商证券（PC）版可完全替代此客户端，为了保护您的合法权益及资金安全，请您点击下方"升级到新版本"按钮进行升级。

**Comment by mymmsc** [comment]
这个只是部分券商的服务节点的弹出来的hello接口的升级提示，如果觉得这个节点有问题，可以删除。
另外，由于github的访问问题，gotdx已经迁移至gitee.com/quant1x/gotdx。
